### ISSUE TITLE
fix(app): VesselDetail.test.ts TypeScript errors after VesselRow type change

### ISSUE THREAD

**Issue by yohei1126** [edgesentry/arktrace#469]
## Problem

The **Deploy App to Cloudflare Pages** workflow fails on the `Build` step with TypeScript errors in `src/components/VesselDetail.test.ts`. Introduced by #466 (esbuild / vitest bump) which triggered `tsc -b` to pick up pre-existing type mismatches.

**Run:** https://github.com/edgesentry/arktrace/actions/runs/24805105347/job/72597234086

### Errors

```
src/components/VesselDetail.test.ts(41,3): error TS2353:
  Object literal may only specify known properties, and
  'sanctions_distance' does not exist in type 'VesselRow'.

src/components/VesselDetail.test.ts(95,56): error TS2322:
  Type 'null' is not assignable to type 'string'.

src/components/VesselDetail.test.ts(100,56): error TS2322:
  Type 'null' is not assignable to type 'string'.

src/components/VesselDetail.test.ts(105,56): error TS2322:
  Type 'null' is not assignable to type 'string'.
```

## Root cause

`VesselRow` no longer contains a `sanctions_distance` field (likely removed in a recent schema change), and several fields that were previously nullable (`string | null`) have been tightened to `string`. The test fixture on line 41 and mock rows on lines 95 / 100 / 105 were not updated to match.

## Fix

- Remove `sanctions_distance` from the test fixture on line 41 (or add it back to `VesselRow` if still needed).
- Replace `null` with an empty string `""` (or the correct sentinel) for the three string fields on lines 95, 100, and 105 of `VesselDetail.test.ts`.
